### ISSUE TITLE
generated.d doesn't compile without trial and arsd-official in `dependencies`

### ISSUE THREAD

**Issue by ohdatboi** [gedaiu/trial#30]
generated.d of simple project (same as in #29) doesn't compile without:
```json
"dependencies": {
  "trial": "~>0.3.1",
  "arsd-official:terminal": "~>1.2.1"
}
```
in dub.json.

**Comment by gedaiu** [comment]
I think I have to embed `arsd-official:terminal`... it's defined as a `sourceLibrary` and this causes some problems... I will think about this issue tomorrow :)
