### ISSUE TITLE
Doesn't compile under 32 bit

### ISSUE THREAD

**Issue by DiddiZ** [gedaiu/trial#34]
Compilation failes with
```
trial_root.d(3818,36): Error: cannot implicitly convert expression `line` of type `long` to `uint`
```
which is caused by `line` being explicitly casted to `long` (`line = postFix[0..idx].to!long;`) and `SourceLocation.line` being declared as `size_t`:
```
struct SourceLocation {
  ...
  size_t line;
  ...
```

I'm using the 32 bit DMD compiler under Windows 7.

**Comment by gedaiu** [comment]
Done! 

Sorry for the inconvenience... I added a x86 build on travis, so this issue should not appear in the future...

**Comment by DiddiZ** [comment]
Thanks for the quick fix, works now.
