### ISSUE TITLE
Configure dependencies needed for testing

### ISSUE THREAD

**Issue by ohdatboi** [gedaiu/trial#8]
`dub test`, for example, automatically uses configuration `unittest`, so it is possible to specify dependencies needed for tests.

Example dub.json:
```
{
	...
	"configurations": [
		...
		{
			"name": "unittest",
			"targetType": "executable",
			"dependencies": {
				"fluent-asserts": "~>0.6.3"
			}
		}
	]
}
```

trial could automatically use configuration `trial` or fall back to `unittest`, so both trial and `dub test` can be used simultaneously.

Also, it would be great to support other dub options in configuration as well (like `excludedSourceFile`, `dflags`, etc).

**Comment by gedaiu** [comment]
it sounds like a great idea! I will be offline for a while, but I will look into this.
